### ISSUE TITLE
sockopts.go uses the wrong type for ZMQ_SNDHWM and ZMQ_RCVHWM

### ISSUE THREAD

**Issue by apanda** [vaughan0/go-zmq#2]
Hi
Currently ZMQ_SNDHWM and ZMQ_RCVHWM are represented as uint64s, while in ZMQ 3.2 they are actually ints. This isn't just a representation issue, the current usage results in an EINVAL.

I have a fix in https://github.com/apanda/go-zmq/blob/master/sockopts.go but I haven't been tracking your changes, and I have a bunch of other "dirty changes". I will clean and issue a pull request eventually, but if you get to it before me the changes should be obvious.

Panda

**Comment by vaughan0** [comment]
Thanks for this. I did update all the socket option methods a while ago to use the correct data types for ZeroMQ 3.2, and if you look at the current code you should see that the Set*HWM methods cast their parameters to ints before passing them to zmq.

**Comment by vaughan0** [comment]
Just for reference, this was the commit: https://github.com/vaughan0/go-zmq/commit/81affac794ec501625ead49e42f822f917b8ca05
