### ISSUE TITLE
SendPart and RecvPart should perhaps handle EINTR and EAGAIN

### ISSUE THREAD

**Issue by apanda** [vaughan0/go-zmq#3]
This issue is identical to http://osdir.com/ml/zermq-development/2012-08/msg00080.html, except when applied to this library. Not having SendPart and RecvPart deal with them is somewhat problematic, since it makes it particularly hard to handle resends with the channel abstraction.

I have a fix at https://github.com/apanda/go-zmq/blob/master/zmq.go but similar to the other issue, in an unclean state, etc.

Panda

**Comment by vaughan0** [comment]
Currently SendPart and RecvPart do handle EINTR, but not EAGAIN. I'm not sure if EAGAIN should be handled, because it is only returned for non-blocking sockets and the channel abstraction doesn't seem to make much sense when used with non-blocking sockets.
